name: Deploy Worker
on:
  push:
  pull_request:
  repository_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    #needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: veRQ8fty26VJTfQRTdvjUV5e8D4GxaQT4TArVHp4
          accountId: 917ef4884c35f1c4e417cc4b607c0071
